[project]
name = "cellfinder-napari"
description = "Efficient cell detection in large images"
readme = "README.md"
authors = [
    {name = "Adam Tyson", email = "code@adamltyson.com"},
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Topic :: Scientific/Engineering :: Image Recognition",
]
requires-python = ">=3.8"
dependencies = [
    "brainglobe-napari-io",
    "cellfinder-core>=0.3",
    "brainglobe-utils",
    "magicgui",
    "napari",
    "napari-ndtiffs",
    "napari-plugin-engine >= 0.1.4",
    "numpy",
    "pooch>=1",
    "qtpy",
    "scikit-image",
    "tifffile",
]
license = {text = "BSD-3-Clause"}
dynamic = ['version']

[project.urls]
Homepage = "https://brainglobe.info/cellfinder"
"Source Code" = "https://github.com/brainglobe/cellfinder-napari"
"Bug Tracker" = "https://github.com/brainglobe/cellfinder-napari/issues"
Documentation = "https://docs.brainglobe.info/cellfinder-napari/"
"User Support" = "https://forum.image.sc/tag/brainglobe"

[project.optional-dependencies]
dev = [
    "black",
    "gitpython",
    "pre-commit",
    "pytest",
    "pytest-cov",
    "pytest-qt",
]

[project.entry-points."napari.manifest"]
cellfinder-napari = "cellfinder_napari:napari.yaml"


[build-system]
requires = [
    "setuptools>=45",
    "wheel",
    "setuptools_scm[toml]>=6.2",
]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = ["cellfinder_napari*"]

[tool.setuptools_scm]

[tool.black]
target-version = ['py38', 'py39', 'py310']
skip-string-normalization = false
line-length = 79

[tool.ruff]
line-length = 79
exclude = ["__init__.py","build",".eggs"]
select = ["I", "E", "F"]
fix = true
